name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  library:
    runs-on: macos-12
    environment: default
    strategy:
      matrix:
        xcode: ['14.2']
        # Swift: 5.7  
    steps:
      - uses: actions/checkout@v3
      - name: Format lint
        run: swiftformat --lint .
      - name: Lint
        run: swiftlint .
