name: linux-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  library:
    runs-on: ubuntu-latest
    environment: default
    
    steps:
      - name: Run Tests
        run: swift test --enable-code-coverage --parallel
