name: macos-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  library:
    runs-on: macos-12
    environment: default
    strategy:
      matrix:
        xcode: ['14.2']
        # Swift: 5.7  
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run Tests
        run: swift test --enable-code-coverage --parallel
      - name: Swift Coverage Report
        run: xcrun llvm-cov export -format="lcov" .build/debug/swift-argument-encodingPackageTests.xctest/Contents/MacOS/swift-argument-encodingPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true # optional (default = false)
